set -eux -o pipefail
ARDUINO_HOME="/usr/share/arduino/hardware/archlinux-arduino"
CORES_DIR="$ARDUINO_HOME/avr/cores/arduino"
INCLUDE_STANDARD="$ARDUINO_HOME/avr/variants/standard"
OUT_DIR="core_dir"
OUT_LIB="core.a"
mkdir -p "$OUT_DIR"
avr-gcc -c -g -x assembler-with-cpp -flto -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/wiring_pulse.S" -o "$OUT_DIR/wiring_pulse.S.o"
avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/wiring_digital.c" -o "$OUT_DIR/wiring_digital.c.o"
avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/hooks.c" -o "$OUT_DIR/hooks.c.o"
avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/WInterrupts.c" -o "$OUT_DIR/WInterrupts.c.o"
avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/wiring_shift.c" -o "$OUT_DIR/wiring_shift.c.o"
avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/wiring_analog.c" -o "$OUT_DIR/wiring_analog.c.o"
avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/wiring_pulse.c" -o "$OUT_DIR/wiring_pulse.c.o"
avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/wiring.c" -o "$OUT_DIR/wiring.c.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/CDC.cpp" -o "$OUT_DIR/CDC.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/HardwareSerial0.cpp" -o "$OUT_DIR/HardwareSerial0.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/Print.cpp" -o "$OUT_DIR/Print.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/USBCore.cpp" -o "$OUT_DIR/USBCore.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/HardwareSerial3.cpp" -o "$OUT_DIR/HardwareSerial3.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/IPAddress.cpp" -o "$OUT_DIR/IPAddress.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/Stream.cpp" -o "$OUT_DIR/Stream.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/HardwareSerial2.cpp" -o "$OUT_DIR/HardwareSerial2.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/HardwareSerial.cpp" -o "$OUT_DIR/HardwareSerial.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/PluggableUSB.cpp" -o "$OUT_DIR/PluggableUSB.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/Tone.cpp" -o "$OUT_DIR/Tone.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/HardwareSerial1.cpp" -o "$OUT_DIR/HardwareSerial1.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/WMath.cpp" -o "$OUT_DIR/WMath.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/WString.cpp" -o "$OUT_DIR/WString.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/abi.cpp" -o "$OUT_DIR/abi.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/main.cpp" -o "$OUT_DIR/main.cpp.o"
avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-I$CORES_DIR" "-I$INCLUDE_STANDARD" "$CORES_DIR/new.cpp" -o "$OUT_DIR/new.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/wiring_pulse.S.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/WInterrupts.c.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/hooks.c.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/wiring.c.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/wiring_analog.c.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/wiring_digital.c.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/wiring_pulse.c.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/wiring_shift.c.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/CDC.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/HardwareSerial.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/HardwareSerial0.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/HardwareSerial1.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/HardwareSerial2.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/HardwareSerial3.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/IPAddress.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/PluggableUSB.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/Print.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/Stream.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/Tone.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/USBCore.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/WMath.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/WString.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/abi.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/main.cpp.o"
avr-gcc-ar rcs "core.a" "$OUT_DIR/new.cpp.o"
